name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-automerge:
    name: Dependabot Auto-Merge
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-pr-dependabot-automerge.yml@feat/unify-provider-auth
    secrets: inherit # pragma: allowlist secret
