name: "Check Terraform"

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [main]

jobs:
  check:
    name: "Reusable Workflow"
    permissions:
      contents: read
      id-token: write
      statuses: write
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-terraform-check.yml@feat/unify-provider-auth
    with:
      auth_method: ${{ startsWith(github.event.repository.name, 'tf-aws') && 'aws' || startsWith(github.event.repository.name, 'tf-az') && 'azure' || 'none' }}
    secrets: inherit # pragma: allowlist secret
