name: Automated Approvals

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: read
  contents: read

jobs:
  automated-approvals:
    name: Automated Approvals
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-pr-automated-approvals.yml@feat/unify-provider-auth
    secrets: inherit # pragma: allowlist secret
