name: Publish Prerelease

on:
  push:
    branches:
      - main

jobs:
  release-on-merge:
    name: "Create and Publish Prerelease on Merge"
    permissions:
      contents: write
      pull-requests: write
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-release-on-merge.yml@0.14.2
    secrets: inherit # pragma: allowlist secret
