name: Pre-Commit Checks

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [main]

jobs:
  pre-commit:
    name: Pre-Commit Checks
    permissions:
      contents: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v6

      - id: setup-python
        name: Set up Python 3.14
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          python-version: 3.14

      - id: install-tools
        name: Install Tools with uv
        run: |
          uv tool install pre-commit --with pre-commit-uv

      # If we've cached the pre-commit environment, restore it based on the hash of the pre-commit config.
      - id: cache
        name: Restore cached pre-commit environment
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - id: pre-commit
        name: Run pre-commit checks
        run: uv run pre-commit run --all-files

      - id: set-status-check
        name: Set Status Check
        if: always()
        uses: launchbynttdata/launch-workflows/.github/actions/update-status-check@feat/unify-terraform-check-workflows
        with:
          check_name: "Pre-Commit Checks"
          status: ${{ steps.pre-commit.outcome == 'success' && 'success' || steps.pre-commit.outcome == 'failure' && 'failure' || 'error' }}
          description: "Pre-Commit Checks ${{steps.pre-commit.outcome }}"
          target_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
